# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vitascopearts.com" # the base hostname & protocol for your site
blogurl: "http://vitascopearts.tumblr.com"
permalink: /:categories/:title

title: Vitascope Arts
description: > # this means to ignore newlines
  Vitascrope Arts is a full service production company, from concept to
  final cut. We help businesses show off their products with attention-grabbing videos.

facebook: "https://www.facebook.com/vitascopearts/"
twitter: "https://twitter.com/vitascopearts"
instagram: "https://www.instagram.com/vitascopearts"
youtube: UC0vPMH-qsWhaskmWM2vW_1g
email: hello@vitascopearts.com
phone: (123) 123-1234

mailto: "mailto:hello@vitascopearts.com?Subject=Hello Vitascope!"


# Build settings
markdown: kramdown
